### ISSUE TITLE
Liked your approach :)

### ISSUE THREAD

**Issue by ldjebran** [omaciel/pytest-fauxfactory#2]
Tested from with pip install 
See it as a replacement for sub tests for many situation.
possible extensions is to pass str_type=callable or str str_type=iterator and have it generate the necessary strings 
```python
def callable():
  return [(str_type1, args1, kwrags1), (str_type2, args2, kwrags2)]

def iterator()
   for t in [(str_type1, args1, kwrags1), (str_type2, args2, kwrags2)]:
       yield t 
```
callable and iterator function can return or yield valid or invalid strings for positive and negative tests.

what do you think?

**Comment by omaciel** [comment]
Thank you @ldjebran :)

I would love to see an example for your proposal. The first thing I wanted to do for this first round was to provide a simple way for people to parameterize their tests, without having to write a lot of code. So, for example, if all I need is a random number of strings, the following code would be enough:

```python
@pytest.mark.gen_string(N)
```

Where `N` is a number representing the number of items to be generated. The value returned is actually a Python generator.

To pass a `callable`, one could modify the `gen_string` function to take a *FauxFactory* method, for example, and then return the values:

```python
@pytest.mark.gen_string(N, fauxfactory.gen_alpha(length=20))
```

This  approach makes sense to me, specially since I have had someone tell me how he would like to have the generator return multiple values per 'row', like such:

```python
@pytest.mark.gen_string(N, callable)
def test_multiple_values(value)
    assert len(value) == 2
    org_name = value[0]
    org_label = value[1]
```

The callable would then return `2` items:

```python
def callable():
    return (fauxfactory.gen_alpha(), fauxfactory.gen_alpha())
```

Making the `callable` itself the generator could simplify the overall signature for the main `gen_string` function:

```python
@pytest.mark.gen_string(callable(N, *args, **kwargs))
```

OK, I wrote a lot already and am sort of getting lost with my thoughts hehe but I like the suggestion and would love to see a PR :)

**Comment by ldjebran** [comment]
The idea has been implemented, and refined in other issues, think we can close this issue
